# Generated by Django 5.2.11 on 2026-02-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'business')},
        ),
    ]
